# file to simplify import
from .Tile1MonasteryMeadow import Tile1
from .Tile2MonasteryMeadowRoad import Tile2
from .Tile3Castle import Tile3
from .Tile4MeadowCastle import Tile4
from .Tile5MeadowCastleShield import Tile5
from .Tile6MeadowRoadCastle import Tile6
from .Tile7MeadowRoadCastleShield import Tile7
from .Tile8MeadowCastle import Tile8
from .Tile9MeadowCastleShield import Tile9
from .Tile10MeadowRoadCastle import Tile10
from .Tile11MeadowRoadCastleShield import Tile11
from .Tile12MeadowCastle import Tile12
from .Tile13MeadowCastleShield import Tile13
from .Tile14MeadowCastle import Tile14
from .Tile15MeadowCastle import Tile15
from .Tile16MeadowCastle import Tile16
from .Tile17MeadowRoadCastle import Tile17
from .Tile18MeadowRoadCastle import Tile18
from .Tile19MeadowRoadCastle import Tile19
from .Tile20MeadowRoadCastle import Tile20
from .Tile21MeadowRoad import Tile21
from .Tile22MeadowRoad import Tile22
from .Tile23MeadowRoad import Tile23
from .Tile24MeadowRoad import Tile24
from .Tile25Start import Tile25
